### ISSUE TITLE
Update app_status function for latest pm2 version 1.1.1

### ISSUE THREAD

**Issue by willaustin** [creative-workflow/capistrano-pm2#1]
It appears that the pm2 `jlist` command no longer (at least in version 1.1.1) takes an application name as a command line argument as per the help `pm2 jlist -h`. This is a problem, then, because the jlist JSON output is simply an array of objects representing ALL the processes. The `app_status` method as it currently stands does not account for this format.

Here is an abbreviated example of the jlist JSON output from pm2 v1.1.1

``` json
[
  {
    "pid": 0,
    "name": "pm2-test",
    "pm2_env": {
      "status": "stopped"
    }
  }
]
```

I've overwritten the `app_status` function in my particular Rake task.

I would like to submit a pull request to update this. Would you be OK with that?

**Comment by tomhanoldt** [comment]
Hey you are welcome, recently we moved to a docker infrastructure and don't use this gem in production anymore.  But i will test it and update the gem if you submit a pull request. 

Thanks for your engagement.

**Comment by tomhanoldt** [comment]
tested, merged and gem update, thanks =)

**Comment by willaustin** [comment]
Thanks for writing this gem!
